services:
  logic:
    build: ./logic-server
    ports:
      - "5001:5000"
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache

  app:
    build: ./app
    ports:
      - "8080:80"
    restart: unless-stopped

  socket:
    build: ./socket-server
    ports:
      - "5002:8080"
    restart: unless-stopped