services:
  logic:
    build: ./logic-server
    ports:
      - "5001:5000"
    restart: unless-stopped

  app:
    build: ./app
    ports:
      - "8080:80"
    restart: unless-stopped

  socket:
    image: node:20
    working_dir: /usr/src/app
    command: ["node", "index.js"]
    ports:
      - "5002:8080"
    volumes:
      - ./socket-server:/usr/src/app
      - /socket-server/node_modules
    restart: unless-stopped